spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jpaspring
    username: postgres
    password: root
  jpa:
    database-plataform: org.hibernate.dialect.PostgresSQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
